[tool.pylint]
max-line-length = 120
disable = [
    "C0111",  # missing-docstring
    "C0103",  # invalid-name
    "C0303",  # trailing-whitespace
    "W0611",  # unused-import
    "R0911",  # Too many return statements
]
ignore = ["CVS"]
indent-string = "    "
output-format = "colorized"
good-names = ["i", "j", "k", "ex", "Run", "_", "id", "fp"]